### ISSUE TITLE
It could be better optimized for browserify-shim

### ISSUE THREAD

**Issue by gradosevic** [romac/react-if#11]
I've installed the library to node packages, and used it with browserify-shim. I have this syntax in package.json:

```
 "browserify-shim": {
 "react-if":{
      "exports":"ReactIf"
    },
  "client": {
      "exports": "Client",
      "depends": [
        "react:React",
        "react-dom:ReactDOM",
        "react-if:ReactIf"
      ]
    }
}
```

In my client file, I have to add these lines on top of the file in order to make it work:

```
var If = ReactIf.If;
var Then = If.Then;
var Else = If.Else;

```

It would be nice to define these variables directly in package.json

**Comment by romac** [comment]
I'm not sure what to do about that, but will gladly accept a pull request with a fix :)

**Comment by timjacobi** [comment]
@gradosevic could you elaborate this a little more please and reference another library that does it, so we can see what implications this has? Thanks!

**Comment by romac** [comment]
Closing this as I cannot take care of it myself, and this issue has been inactive for a while. Feel free to re-open it to discuss this further. I'll also gladly accept a PR :)
