### ISSUE TITLE
How is this different from jsx-control-statements library? 

### ISSUE THREAD

**Issue by nelsieborja** [romac/react-if#126]
https://github.com/AlexGilleran/jsx-control-statements

**Comment by favna** [comment]
This is purely a React library that doesn't require modifying your Babel config. Therefore it can be used with something like create-react-app which doesn't allow a custom Babel config at all, or NextJS v12 which uses Swc instead of Babel.

TL;DR: Doesn't require babel

**Comment by nelsieborja** [comment]
@favna, thank you for sharing this very detailed comparison with some insightful info. Great work!
