### ISSUE TITLE
Unable to handle null

### ISSUE THREAD

**Issue by jonfairbanks** [romac/react-if#19]
Previously discussed under Issue #18, I have a scenario that react-if doesn't seem to handle appropriately. 

```
console.log(this.props.ticket); // Output = null

<If condition={this.props.ticket === 'null' || null}>
    <Then>
        <div id="noData" style={style.noData}>
            No details found for the given ticket
        </div>
    </Then>
    <Else>
        {this.props.ticket.map(function(data,i) {
            return (
                // Do something with this.props.ticket here
            )
        }, this)}
    </Else>
</If>
```

In my case, I have a props which has been verified to be equal to `null`. As seen above, I have created an if condition to **not** show data if the props is null. 

However, regardless of this logic, the `this.props.ticket.map` inside `<Else>` is run in all cases. This then leads to a `TypeError: Cannot read property 'map' of null` error which prevents our app from rendering. 

From the previous discussion, this is due to React having eager evaluation. It was suggested that we re-write our component to be like so:

```
<If condition={this.props.ticket === null}>
    <Then>
        <div id="noData" style={style.noData}>
            No details found for the given ticket
        </div>
    </Then>
    <Else>{function() {
        return this.props.ticket.map(function(data,i) {
            return (
                // Do something with this.props.ticket here
            )
        }, this)
    }}</Else>
</If>
```

Unfortunately, this does not work either and being unable to check for null has become a blocker for multiple areas of our project. 

Any additional suggestions for getting around this issue? Is this something that React-if could gracefully catch?

**Comment by romac** [comment]
Sorry for the late reply. 

It looks to me like the issue might come from `this.props` not being defined inside the function declared in the Else branch. This is a known JavaScript *feature/quirk*.

To fix it, you might want to try the following:

```javascript
<If condition={this.props.ticket === null}>
    <Then>
        <div id="noData" style={style.noData}>
            No details found for the given ticket
        </div>
    </Then>
    <Else>{function() {
        return this.props.ticket.map(function(data,i) {
            return (
                // Do something with this.props.ticket here
            )
        }, this)
    }.bind(this)}</Else>
</If>
```

Notice the `.bind(this)` after the function declaration in the Else branch.

If you are using an ES2015 to ES5 transpiler (such as [Babel](https://babeljs.io)) you can also do the following:

```javascript
<If condition={this.props.ticket === null}>
    <Then>
        <div id="noData" style={style.noData}>
            No details found for the given ticket
        </div>
    </Then>
    <Else>{() =>
        this.props.ticket.map((data, i) =>
            (
                // Do something with this.props.ticket here
            )
        )
    }</Else>
</If>
```

which will auto-bind the function to the parent scope. You can take a look at any of these links for more info about this feature:

- https://strongloop.com/strongblog/an-introduction-to-javascript-es6-arrow-functions/
- https://babeljs.io/docs/plugins/transform-es2015-arrow-functions/
- https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Functions/Arrow_functions

**Comment by timjacobi** [comment]
@jonfairbanks Is this issue resolved for you?

**Comment by jonfairbanks** [comment]
Ended up having to take a different approach.
