### ISSUE TITLE
Then and Else have different allowance for child nodes

### ISSUE THREAD

**Issue by pronebird** [romac/react-if#21]
Hi,

Consider the following snippet:

```js
<If condition={ parseInt(Math.random() * 100) % 2 == 0 }>
   <Then>{ "They killed Kenny!" }</Then>
   <Else>{ "You don't win friends with salad" }</Else>
</If>
```

`Then` works very well with single text fragment, however `Else` does not.

>Uncaught Error: Else.render(): A valid React element (or null) must be returned. You may have returned undefined, an array or some other invalid object.

**Comment by dattran92** [comment]
I don't think it's possible since a react component can not return a plain text.
Why don't you wrap your text inside a span?

**Comment by pronebird** [comment]
@dattran92  I don't think you read the issue description, quote:

>Then works very well with single text fragment, however Else does not.

Also see Example at https://github.com/romac/react-if

**Comment by dattran92** [comment]
For me, both Then and Else does not work with single text fragment. And I think it's not possible. Will try again later.

**Comment by pronebird** [comment]
It should work if you have div around `If` block.

**Comment by dattran92** [comment]
`
<div>
    <If condition={true}>
        <Then>{ 'True' }</Then>
        <Else>{ 'False' }</Else>
    </If>
</div>
`
never works for me.

**Comment by pronebird** [comment]
That's what I am saying. `Else` does not work, but `If` can easily return single fragment, i.e:

```
<div>
    <If condition={true}>
        <Then>{ 'True' }</Then>
    </If>
</div>
```

Please, try an example from README.

**Comment by dattran92** [comment]
The same with my example, but not work for me.

**Comment by romac** [comment]
Should be fixed now. Feel free to re-open if still an issue with v3.0.0
