### ISSUE TITLE
re-render bug

### ISSUE THREAD

**Issue by Canoir** [romac/react-if#212]
Hi,
Why when the "if" tag condition is false it will render the "Then" Tag? that's too much re-rendering...

**Comment by favna** [comment]
Can you please provide a reproducible code sample for this?

---

Also in general please follow some guidelines for asking technical questions:


When asking for help, make sure to provide as much detail as possible. What have you tried so far? Do you have stacktraces that you can show us? What are you trying to achieve? Try to answer these questions and others, so we do not have to ask for them afterwards.
> ❯ For a good guide on how to ask questions, see [the instructions that StackOverflow gives](<https://stackoverflow.com/help/how-to-ask>). You should try to always follow these guidelines.
> ❯ For an excellent video that shows how **not** to ask technical questions is this, watch [this YouTube video by LiveOverflow](<https://youtu.be/53zkBvL4ZB4>). 
> ❯ [Asking technical questions (Clarkson)](<https://www.cs.cornell.edu/courses/cs3110/2017fa/thoughtful.html>)
> ❯ [How to ask questions the smart way (Raymond)](<http://www.catb.org/~esr/faqs/smart-questions.html>)

**Comment by favna** [comment]
Closing this due to lack of response from author
