### ISSUE TITLE
request: React-if is not code coverage friendly

### ISSUE THREAD

**Issue by rmit-s3630120-luke-mason** [romac/react-if#227]
### Is there an existing issue or pull request for this?

- [X] I have searched the existing issues and pull requests

### Feature description

I am annoyed that react-if does not present itself as a branch in the code between if else and when and unless, for code coverage tools. && is treated as a branch where as a when is not.

### Desired solution

Is it possible to code the implementation of the children of the conditional components to come up as branches in c8 coverage tooling. otherwise we cannot use react-if for serious projects

### Alternatives considered

Removing react-if and just using && and || logic again

**Comment by favna** [comment]
Closing this as not planned due to lack of response from creator
