### ISSUE TITLE
bug: Geting Error : Support for defaultProps will be removed from function components in a future major release. Use JavaScript default parameters instead.

### ISSUE THREAD

**Issue by HeppyAndriawan** [romac/react-if#261]
First of all, I am creating the app using Next.js 13 with the app directory. During development I get an error while I use Switch, Default, and Case components from React-if and the error says:

" Support for defaultProps will be removed from function components in a future major release. Use JavaScript default parameters instead. "

Here is my code:

![code](https://user-images.githubusercontent.com/47684573/231830391-a3ac3fb0-6971-42bb-bca8-7724b47eb790.png)

and when I delete the React-if component then the error disappears.

Also, regarding this announcement (https://github.com/reactjs/rfcs/pull/107) that is true defaultProps will be moved to class render in React.

So can anyone update the module or tell me how to fix this error manually? 

Thanks

**Comment by favna** [comment]
Hai, thanks for the report. I was unaware of this React RFC. Do you think you can make a PR to fix the issue? The relevant code is this and it's also used in some of the other files: https://github.com/romac/react-if/blob/master/src/Case.tsx#L12-L14

I'm pretty busy on average so if you can make a PR that would be great, if not then I'll get around it eventually but I cannot promise when.

**Comment by favna** [comment]
Resolved in #279
