### ISSUE TITLE
! Build fails

### ISSUE THREAD

**Issue by meszaros-lajos-gyorgy** [romac/react-if#33]
The issue name is self explainatory: travis fails to build due to outdated dependencies in the repo.

Travis fails with the following message:

`Error: react-addons-test-utils is an implicit dependency in order to support react@0.13-14. Please add the appropriate version to your devDependencies. See https://github.com/airbnb/enzyme#installation`

Also, node 5 and 6 should be updated too.

**Comment by meszaros-lajos-gyorgy** [comment]
Hello? Is this project still alive?

**Comment by meszaros-lajos-gyorgy** [comment]
bump

**Comment by romac** [comment]
Fixed in #32. Thanks!
