### ISSUE TITLE
If's children props get evaluated if if the condition is false

### ISSUE THREAD

**Issue by lishine** [romac/react-if#39]
And so it behaves not like {xxx &&
I hope explaining myself well :)

**Comment by romac** [comment]
You can wrap the children of `<Then>` and `<Else>` in a function to suspend evaluation like so:

```jsx
<If condition={false}
  <Then>{() => {
    console.log("never printed");
    "When true"
  }}</Then>
  <Else>{() => {
    "When false"
  }}</Else>
</If>
```

Sorry, this is something that used to be mentioned in the README and got lost in recent updates, I'll add it back to the README as soon as possible.

**Comment by schotime** [comment]
Couldn't this have a property on the if of whether to delay execution?
