### ISSUE TITLE
maybe PropTypes.bool.isRequired to PropTypes.any.isRequired ?

### ISSUE THREAD

**Issue by prostoVladislav** [romac/react-if#41]
`<When condition={array.length}>do something</When> 
`
console error

**Comment by meszaros-lajos-gyorgy** [comment]
Just to note: PropTypes.bool is used throughout the project for every condition property.

**Comment by meszaros-lajos-gyorgy** [comment]
I would definitely leave it as a boolean parameter, since having propTypes.any as a component kinda looses the purpose of having propTypes in the first place. This particular case of checking whether the array is empty can be easily fixed by prepending double negation: `!!array.length`

**Comment by romac** [comment]
I agree with @meszaros-lajos-gyorgy. I'd rather have more rather than less "type safety", especially when it's as easy as `!!array.length` to work around it.

My two cents: Use `array.length != 0`, which is only 4 characters longer and conveys the intent much better imho.
