### ISSUE TITLE
Support promise condition

### ISSUE THREAD

**Issue by gera2ld** [romac/react-if#53]
**Motivation:** When the condition is a Promise or an asynchronous callback, we cannot get the result immediately and have to wrap the children in another high order component. I think this is exactly the reason why I need an `<If>` component.

So I suggest the `<If>` component to support asynchronous conditions:

```js
<If condition={Promise.resolve(true)}>
  The promise is resolved with `true`.
</If>
```

**Comment by romac** [comment]
Sounds like a good idea! I'll happily accept a PR which implements this :)
