### ISSUE TITLE
Expressions are still executed in a failed <If>

### ISSUE THREAD

**Issue by EliotSlevin** [romac/react-if#63]
Here's a common use case for an if component - checking if something exists before looping through it, e.g. data from a server that could be an array but also could be empty. 

```
const data = null

<If condition={data}>
   <p>I will not render as expected</p>
   {data.map((item) => // this line executes anyway, causing a crash
        ....
   )}
</If>
```

Even though the condition worked as expected, stoping the `<p>` from rendering, the expression is executed anyway?

**Comment by romac** [comment]
To delay evaluation of children, much like conditions, you can wrap them in a closure, as [documented](https://github.com/romac/react-if#delaying-evaluation-of-children--condition) (although not very welll, I admit).


```js
<If condition={data}>{ () => 
  <>
     <p>I will not render as expected</p>
     {data.map((item) => ....)} // won't be executed
  <>
}</If>
```

**Comment by EliotSlevin** [comment]
Oh perfect!

I did briefly scan that in the docs, but as it said ‘delay’ not stop I
thought it wouldn’t help me.

**Comment by Favna** [comment]
For as far as I can tell this has been sufficiently answered so I'm closing it. If I'm wrong, feel free to re-open the issue.
