### ISSUE TITLE
[Suggestion]: Take over maintenance (to support the community)

### ISSUE THREAD

**Issue by Favna** [romac/react-if#64]
Hello Romac, I'm a great fan of this library and use it in several projects. However as you listed in the repo's description, you are no longer maintaining it.

For everyone in the community that uses your package (which is a lot if download count is anything to go by: https://www.npmtrends.com/react-if) I want to propose that I'd take over maintenance.

If you're up for this process, I have also attempted to contact you on Twitter (my handle is [`@favna_`](https://twitter.com/favna_)) and I would suggest we talk further details there, privately.

**Comment by romac** [comment]
@Favna Feel free to close this once you made sure you have the necessary access rights. And thanks again for offering your help :)

**Comment by Favna** [comment]
I can confirm it
