### ISSUE TITLE
if/then/else is not compatible with Ant Design's Form

### ISSUE THREAD

**Issue by cat-walk** [romac/react-if#88]
First of all, I realy love this package. 
But today I found that it's not compatible with Ant Design's Form, more accurately, the component Form.Item innner If/Else/Then can't be collected by Ant Design's Form. I hope that somebody can tell me if it should be resolved by "react-if"? Or maybe I should ask the Ant Design's developer for help?

As what I list, the ternary operator works well with Ant Design （Ant Design is a UI component framework which is widely used.）
![image](https://user-images.githubusercontent.com/16714322/116184740-f422a480-a752-11eb-9a1c-fcc856cfe580.png)

**Comment by cat-walk** [comment]
I printed the values collected by antd's form, and found the problem.

![image](https://user-images.githubusercontent.com/16714322/116185235-cb4edf00-a753-11eb-8b44-7a66b7e1c4d8.png)

**Comment by Favna** [comment]
So.. what was the problem? I have never used antd before so I'm a bit puzzled. Maybe try the "delaying execution" syntax as described in the readme? The thing with react-if as oppossed to ternary operators is that by default both paths are executed but only 1 is shown. You need to delay execution to resolve that if it is a problem.

**Comment by Favna** [comment]
Closing due to lack of response
