### ISSUE TITLE
It should be allowed to provide any content to If component without wrapping it in Then component

### ISSUE THREAD

**Issue by smashercosmo** [romac/react-if#9]
In simple cases you should be able to do something like this
```javascript
<If condition={true}>
  <div>Hello</div>
</If>
```

**Comment by romac** [comment]
Agreed, that would be a nice feature to have. Sadly, I cannot take care of it at the moment but would gladly accept a pull request :)

**Comment by smashercosmo** [comment]
Ok, I'll make a PR on weekends

**Comment by timjacobi** [comment]
I have address this in #15

**Comment by romac** [comment]
Fixed in #15. Thanks @timjacobi!
